### PR TITLE
Retroactively add sounds

### PR DESCRIPTION
**Pull request by S-N00B-1**
Because most buttons use the "minecraft-button" class the modified script will retroactively add the click sound to all buttons.

Also adds a hover sound.

### CODE REVIEW

**Comment by S-N00B-1** [comment]
This should resolve [buttons going to other parts of lem Site don't make noise](https://discord.com/channels/860805393441357834/1046748212725293106).

**Comment by S-N00B-1** [comment]
Running on two braincells here.

**Comment by S-N00B-1** [comment]
Okay, should actually work now. Sorry about that.

**Comment by DBTDerpbox** [comment]
slight issue, hovering over buttons rapidly does not play sounds the way you'd expect, it waits for the current sound to stop instead of interrupting it or playing it twice

this issue already existed in the past with the music easter egg, but its a lot more visible now

https://user-images.githubusercontent.com/65347035/208635966-f9a5fbc9-fdf6-4685-865f-7314004800ea.mp4

**Comment by S-N00B-1** [comment]
I’ll look into it.

**Comment by S-N00B-1** [comment]
I’ll need to do something with clone node, this might take me awhile.

**Comment by DBTDerpbox** [comment]
feel free to take as long as you need

**Comment by S-N00B-1** [comment]
As far as I know, this should work now.

**Comment by DBTDerpbox** [comment]
it is no longer possible to click on buttons

https://user-images.githubusercontent.com/65347035/208737718-91aa141c-8697-4ab7-90ab-c8d42e302aa9.mp4

**Comment by S-N00B-1** [comment]
How the?

**Comment by S-N00B-1** [comment]
This works on my machine, I think it actually functions now, for real.

**Comment by DBTDerpbox** [comment]
works now, its up to you if you want to fix the menu music easter egg

**Comment by S-N00B-1** [comment]
What was the issue with that?

**Comment by DBTDerpbox** [comment]
spam clicking it causes the behavior of it waiting for the sound to end

**Comment by S-N00B-1** [comment]
I'm going to go with not fixing it, if that's okay.

**Comment by DBTDerpbox** [comment]
alright

**Pull request merged**
