### PR TITLE
Restructure Other Contributions

### PR DESCRIPTION
**Pull request by S-N00B-1**
image

### CODE REVIEW

**Comment by DBTDerpbox** [comment]
Looks good, however I do realize we haven't added your trailer to the credits and I'm slightly unsure where to put them

**Comment by S-N00B-1** [comment]
Asset contributions? or maybe Special Thanks? Unsure.

**Comment by PixeoGames** [comment]
how about general specifics in a main category then have a hover / dropdown for all subgoals / contributions?
That or we can have a Meet the Developers / Contributors page that just has all major project contributors, bios, storys, whatever. Idk, seems cool

**Comment by PixeoGames** [comment]
Alike the hyperlink. Contributors can write their page and make a bio / contributions list or whatever

**Comment by DBTDerpbox** [comment]
I was very much considering how to incorporate something like that, the issue is I know *absolutely nothing* about web design

**Pull request merged**
