### PR TITLE
Theme Patch

### PR DESCRIPTION
**Pull request by S-N00B-1**

### CODE REVIEW

**Comment by DBTDerpbox** [comment]
still considering using the 1.3 music instead of 1.4 since the old logo

other than that, once the menu server easter egg is fixed itll get merged

**Comment by S-N00B-1** [comment]
I think I fixed the things. Maybe.

**Comment by DBTDerpbox** [comment]
Will check, hold on

**Comment by DBTDerpbox** [comment]
Could you merge the newer version of the website into this PR?

**Comment by S-N00B-1** [comment]
That should do it.

**Comment by DBTDerpbox** [comment]
Uh... This breaks global website themes

image

**Comment by DBTDerpbox** [comment]
Seems to actually breaks themes in general

image

**Pull request closed without merging**
